services:
  # WordPress Service
  wordpress:
    # Use Official Image
    image: ghcr.io/reclaimergold/ftg-wordpress:latest
    
    # Set the User:Group
    user: "1000:1000"

    # Add this line to handle permissions automatically
    init: true

    # This ensures the Memcached service is started before WordPress
    depends_on:
      - memcached

    # Support HTTP/HTTPS Ports
    ports:
      - ${PORT}:80

    # Restart unless explicitly stopped by the user
    restart: unless-stopped

    # Set Environment Variables
    environment:
      - WORDPRESS_DB_HOST=${WP_HOST}:30771
      - WORDPRESS_DB_USER=${WP_USER}
      - WORDPRESS_DB_PASSWORD=${WP_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_DB_PREFIX}
      - WORDPRESS_DEBUG=${WP_DEBUG_ENABLED}
      # This block injects the necessary configuration into your wp-config.php
      # to connect WordPress to the Memcached container.
      # IMPORTANT: For this to work, you must also install a Memcached plugin
      # in your WordPress admin dashboard, such as "W3 Total Cache" or "Memcached Object Cache".
      - >
        WORDPRESS_CONFIG_EXTRA=
        define('WP_CACHE', true);
        define('W3TC_CONFIG_CACHE_ENGINE', 'memcached');
        define('W3TC_CONFIG_CACHE_MEMCACHED_SERVERS', 'memcached:11211');
        define('W3TC_CONFIG_DATABASE', true);

    # Map Disks / Storage Locations to Local Server
    volumes:
      - /docker/wordpress/${USER_ACCOUNT}/wp-content:/var/www/html/wp-content
      - /docker/wordpress/${USER_ACCOUNT}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    # Add this section to allocate resources to WordPress
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
        reservations:
          cpus: '6.0'
          memory: 6G

  # Memcached Service
  memcached:
    # Use the official Memcached image
    image: memcached:latest

    # Restart unless explicitly stopped by the user
    restart: unless-stopped

    # Add this section to allocate resources to Memcached
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M